import pygame

# bomb
bomb1_img = pygame.image.load("resources/image_bomb/firecracker_1.png")
bomb2_img = pygame.image.load("resources/image_bomb/firecracker_2.png")
bomb3_img = pygame.image.load("resources/image_bomb/firecracker_3.png")
bomb4_img = pygame.image.load("resources/image_bomb/firecracker_4.png")
bomb5_img = pygame.image.load("resources/image_bomb/firecracker_5.png")
bomb6_img = pygame.image.load("resources/image_bomb/firecracker_6.png")
bomb7_img = pygame.image.load("resources/image_bomb/firecracker_7.png")
bomb8_img = pygame.image.load("resources/image_bomb/firecracker_8.png")
bomb9_img = pygame.image.load("resources/image_bomb/firecracker_9.png")
# explode
explode1_img = pygame.image.load("resources/image_bomb/explode_1.png")
explode2_img = pygame.image.load("resources/image_bomb/explode_2.png")
explode3_img = pygame.image.load("resources/image_bomb/explode_3.png")
explode4_img = pygame.image.load("resources/image_bomb/explode_4.png")
explode5_img = pygame.image.load("resources/image_bomb/explode_5.png")
explode6_img = pygame.image.load("resources/image_bomb/explode_6.png")
explode7_img = pygame.image.load("resources/image_bomb/explode_7.png")
explode8_img = pygame.image.load("resources/image_bomb/explode_8.png")
explode9_img = pygame.image.load("resources/image_bomb/explode_9.png")
# bad guy
nian0_img = pygame.image.load("resources/image_badguy/nian_0.png")
nian1_img = pygame.image.load("resources/image_badguy/nian_1.png")
nian2_img = pygame.image.load("resources/image_badguy/nian_2.png")
nian3_img = pygame.image.load("resources/image_badguy/nian_3.png")
nian4_img = pygame.image.load("resources/image_badguy/nian_4.png")
nian5_img = pygame.image.load("resources/image_badguy/nian_5.png")
lavae1_img = pygame.image.load("resources/image_badguy/Lavae_1.png")
lavae2_img = pygame.image.load("resources/image_badguy/lavae_2.png")
zombies1_img = pygame.image.load("resources/image_badguy/zombie_1.png")
critter1_img = pygame.image.load("resources/image_badguy/critter_1.png")
dragonfly_0_img = pygame.image.load("resources/image_badguy/dragonfly_0.png")
boss_normal_img = pygame.image.load("resources/image_badguy/dragonfly_1.png")
boss_angry_img = pygame.image.load("resources/image_badguy/dragonfly_2.png")
fire_ball_img = pygame.image.load("resources/image_badguy/fire_ball_1.png")
# main
heart_img = pygame.image.load("resources/image_main/heart.png")
lawn_img = pygame.image.load("resources/image_main/lawn.jpg")
game_over_img = pygame.image.load("resources/image_main/game over.png")
game_win_img = pygame.image.load("resources/image_main/win.png")
# player
player_img = pygame.image.load("resources/image_player/player_run.png")
